version: '3.8'

services:
  app:
    build: .
    ports:
      - "10100:10100"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
