name: Deploy to Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        timeout : 60s
        script: |
          echo "##### START #####"
          cd ~/GCP-TEAM4
          
          echo "##### GIT PULL #####"
          git pull origin main

          echo "##### DOCKER DOWN #####"
          docker compose down

          echo "##### DOCKER UP #####"
          docker compose up -d
        debug: true
